name: Get secrets

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Secret in Workflow
        run: echo ${{ secrets.FIREBASECONFIG }}
